name:  Build and Test C++ and Python

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        python-version: [ '2.7', '3.5', '3.6', '3.7', '3.10' ]
        os: ['ubuntu-20.04', 'ubuntu-latest']
        exclude:
             - python-version: 3.5
               os: ubuntu-latest
             - python-version: 3.6
               os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    name: Build and test with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install -r requirements.txt .
          python test.py
          yes | python -m pip uninstall dash-hash
